# Generated by Django 4.2.8 on 2024-10-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_price_2_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price_2',
            new_name='discount',
        ),
    ]
