# Generated by Django 4.2.8 on 2024-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_price_2_products_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discount',
            new_name='price_2',
        ),
    ]
