# Generated by Django 4.2.8 on 2024-10-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_rename_discount_products_price_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price_2',
            new_name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
